### ISSUE TITLE
Why a port of Python itself?

### ISSUE THREAD

**Issue by guettli** [nascheme/ppython#1]
I am unsure if the current approach is the most easy one.

I like the "coding: ..." trick done by some tools.

See:  http://stackoverflow.com/questions/20992179/how-does-coding-pyxl-work-in-python

One solution for porting code to python3 could be this:

`coding: python2`

The "python2" codec parses the python2 source and creates python3 output for the python3 interpreter.

I guess (don't know) that this approach is easier than forking python.

What do you think?

**Comment by nascheme** [comment]
Anything the "coding:" trick can do, 2to3 can also do.  So, it is not useful for me.  The porting problems I'm targeting can only be detected at runtime.  For example, comparisons that end up using the default Python 2 behavior.  Or, passing a bytes object to an API that expects a str or vis-versa.

**Comment by guettli** [comment]
@nascheme  thank you for the explanation.
